remote_theme: raviriley/agency-jekyll-theme

domain: w2cxm.github.io
url    : https://w2cxm.github.io 
baseurl: ""

title      : W2CXM
email      : hamradio-l-request@cornell.edu
description: "Amateur Radio Club at Cornell University"
logo:     
  path: assets\img\logo.jpeg
  height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"

plugins:
  - jekyll-remote-theme